use crate::github::{Release, ReleaseAsset, RepoMetadata};
use anyhow::{Result, anyhow};
use std::collections::BTreeMap;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PluginScaffold {
    pub plugin_name: String,
    pub file_name: String,
    pub contents: String,
}

pub fn build_plugin_scaffold(
    repo: &str,
    metadata: &RepoMetadata,
    release: &Release,
) -> Result<PluginScaffold> {
    let (owner, repo_name) = split_repo(repo)?;
    let plugin_name = sanitize_plugin_name(repo_name);
    let description = metadata.description.as_deref().unwrap_or("");
    let assets: Vec<&ReleaseAsset> = release
        .assets
        .iter()
        .filter(|asset| !is_auxiliary_asset(&asset.name))
        .collect();

    if assets.is_empty() {
        return Err(anyhow!(
            "Release '{}' for {owner}/{repo_name} does not contain any installable assets",
            release.tag_name
        ));
    }

    let checksum_pattern = infer_checksum_pattern(&release.assets, &release.tag_name);
    let target_map = infer_targets(&assets);
    let asset_pattern = infer_asset_pattern(&assets, &release.tag_name, &target_map)
        .unwrap_or_else(|| assets[0].name.clone());
    let binary_path = infer_binary_path(&plugin_name, &asset_pattern);

    let mut contents = String::new();
    contents.push_str("# Generated by `scpr plugins new`\n");
    contents.push_str("# Review the patterns below before using this plugin.\n");
    contents.push_str("[plugin]\n");
    contents.push_str(&format!("name = \"{}\"\n", plugin_name));
    contents.push_str(&format!("alias = [\"{}\"]\n", repo_name.replace('_', "-")));
    if description.is_empty() {
        contents.push_str("description = \"\"\n");
    } else {
        contents.push_str(&format!("description = {:?}\n", description));
    }
    contents.push_str(&format!("location = \"github:{owner}/{repo_name}\"\n"));
    contents.push_str(&format!("asset_pattern = \"{}\"\n", asset_pattern));
    if let Some(checksum_pattern) = checksum_pattern {
        contents.push_str(&format!(
            "checksum_asset_pattern = \"{}\"\n",
            checksum_pattern
        ));
    }
    contents.push_str(&format!("binary = \"{}\"\n", binary_path));
    contents.push_str("man_pages = []\n");

    if !target_map.is_empty() {
        contents.push_str("\n[plugin.targets]\n");
        for (platform, target) in target_map {
            contents.push_str(&format!("{:?} = {:?}\n", platform, target));
        }
    }

    Ok(PluginScaffold {
        plugin_name: plugin_name.clone(),
        file_name: format!("{plugin_name}.toml"),
        contents,
    })
}

fn split_repo(repo: &str) -> Result<(&str, &str)> {
    let repo = repo.strip_prefix("github:").unwrap_or(repo);
    let (owner, name) = repo.split_once('/').ok_or_else(|| {
        anyhow!("Expected GitHub repository in the form <owner>/<repo>")
    })?;
    if owner.is_empty() || name.is_empty() || name.contains('/') {
        return Err(anyhow!(
            "Expected GitHub repository in the form <owner>/<repo>"
        ));
    }
    Ok((owner, name))
}

fn sanitize_plugin_name(repo_name: &str) -> String {
    repo_name
        .trim()
        .trim_end_matches(".git")
        .to_ascii_lowercase()
        .replace('_', "-")
}

fn is_auxiliary_asset(name: &str) -> bool {
    let name = name.to_ascii_lowercase();
    name.contains("sha256")
        || name.contains("checksums")
        || name.contains("checksum")
        || name.ends_with(".sig")
        || name.ends_with(".minisig")
        || name.ends_with(".pem")
        || name.ends_with(".sbom")
        || name.ends_with(".txt")
}

fn infer_checksum_pattern(assets: &[ReleaseAsset], tag: &str) -> Option<String> {
    let sidecar = assets.iter().find(|asset| {
        let lower = asset.name.to_ascii_lowercase();
        lower.contains("sha256")
            || lower.contains("checksums")
            || lower.contains("checksum")
    })?;
    let target = detect_platform(&sidecar.name).map(|(_, target)| target);
    Some(replace_common_tokens(&sidecar.name, tag, target.as_deref()))
}

fn infer_targets(assets: &[&ReleaseAsset]) -> BTreeMap<String, String> {
    let mut targets = BTreeMap::new();
    for asset in assets {
        if let Some((platform_key, target_value)) = detect_platform(&asset.name) {
            targets.entry(platform_key).or_insert(target_value);
        }
    }
    targets
}

fn infer_asset_pattern(
    assets: &[&ReleaseAsset],
    tag: &str,
    _targets: &BTreeMap<String, String>,
) -> Option<String> {
    for asset in assets {
        if let Some((_, target_value)) = detect_platform(&asset.name) {
            return Some(replace_common_tokens(
                &asset.name,
                tag,
                Some(target_value.as_str()),
            ));
        }
    }

    assets
        .first()
        .map(|asset| replace_common_tokens(&asset.name, tag, None))
}

fn replace_common_tokens(
    asset_name: &str,
    tag: &str,
    target_value: Option<&str>,
) -> String {
    let version = tag.strip_prefix('v').unwrap_or(tag);
    let mut pattern = asset_name.to_string();

    if let Some(target_value) = target_value {
        pattern = pattern.replacen(target_value, "{target}", 1);
    }

    let candidates = [tag, version];
    for candidate in candidates {
        if !candidate.is_empty() && pattern.contains(candidate) {
            pattern = pattern.replacen(candidate, "{version}", 1);
            return pattern;
        }
    }

    pattern
}

fn infer_binary_path(plugin_name: &str, asset_pattern: &str) -> String {
    if looks_like_archive(asset_pattern) {
        let stem = archive_root(asset_pattern);
        format!("{stem}/{plugin_name}")
    } else {
        plugin_name.to_string()
    }
}

fn looks_like_archive(asset_name: &str) -> bool {
    [
        ".tar.gz",
        ".tgz",
        ".tar.xz",
        ".txz",
        ".tar.zst",
        ".tar.zstd",
        ".tar.bz2",
        ".tbz2",
        ".zip",
    ]
    .iter()
    .any(|suffix| asset_name.ends_with(suffix))
}

fn archive_root(asset_name: &str) -> String {
    for suffix in [
        ".tar.gz",
        ".tgz",
        ".tar.xz",
        ".txz",
        ".tar.zst",
        ".tar.zstd",
        ".tar.bz2",
        ".tbz2",
        ".zip",
    ] {
        if let Some(stem) = asset_name.strip_suffix(suffix) {
            return stem.to_string();
        }
    }
    Path::new(asset_name)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or(asset_name)
        .to_string()
}

fn detect_platform(asset_name: &str) -> Option<(String, String)> {
    let normalized = asset_name.to_ascii_lowercase();
    let mapping = [
        (
            "linux-x86_64",
            &[
                "x86_64-unknown-linux-musl",
                "x86_64-unknown-linux-gnu",
                "linux_amd64",
                "linux-amd64",
                "linux64",
            ][..],
        ),
        (
            "linux-aarch64",
            &[
                "aarch64-unknown-linux-musl",
                "aarch64-unknown-linux-gnu",
                "linux_arm64",
                "linux-arm64",
            ][..],
        ),
        (
            "macos-x86_64",
            &[
                "x86_64-apple-darwin",
                "darwin_amd64",
                "darwin-amd64",
                "macos-amd64",
            ][..],
        ),
        (
            "macos-aarch64",
            &[
                "aarch64-apple-darwin",
                "darwin_arm64",
                "darwin-arm64",
                "macos-arm64",
            ][..],
        ),
        (
            "windows-x86_64",
            &["x86_64-pc-windows-msvc", "windows_amd64", "windows-amd64"][..],
        ),
    ];

    for (platform, targets) in mapping {
        for target in targets {
            if normalized.contains(target) {
                return Some((platform.to_string(), (*target).to_string()));
            }
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::{
        PluginScaffold, build_plugin_scaffold, detect_platform, infer_binary_path,
        replace_common_tokens,
    };
    use crate::github::{Release, ReleaseAsset, RepoMetadata};

    fn sample_release(assets: &[&str]) -> Release {
        Release {
            tag_name: "v1.2.3".to_string(),
            assets: assets
                .iter()
                .map(|name| ReleaseAsset {
                    name: (*name).to_string(),
                    browser_download_url: format!("https://example.com/{name}"),
                    size: 123,
                    digest: None,
                })
                .collect(),
        }
    }

    fn sample_metadata() -> RepoMetadata {
        RepoMetadata {
            default_branch: "main".to_string(),
            description: Some("A friendly tool".to_string()),
        }
    }

    #[test]
    fn test_replace_common_tokens_prefers_target_and_version() {
        let pattern = replace_common_tokens(
            "fd-v1.2.3-x86_64-unknown-linux-musl.tar.gz",
            "v1.2.3",
            Some("x86_64-unknown-linux-musl"),
        );
        assert_eq!(pattern, "fd-{version}-{target}.tar.gz");
    }

    #[test]
    fn test_detect_platform_matches_raw_binary_names() {
        let detected = detect_platform("jq-macos-arm64").unwrap();
        assert_eq!(detected.0, "macos-aarch64");
        assert_eq!(detected.1, "macos-arm64");
    }

    #[test]
    fn test_infer_binary_path_for_archive() {
        assert_eq!(
            infer_binary_path("fd", "fd-{version}-{target}.tar.gz"),
            "fd-{version}-{target}/fd"
        );
    }

    #[test]
    fn test_build_plugin_scaffold_for_archive_release() {
        let scaffold = build_plugin_scaffold(
            "sharkdp/fd",
            &sample_metadata(),
            &sample_release(&[
                "fd-v1.2.3-x86_64-unknown-linux-musl.tar.gz",
                "fd-v1.2.3-aarch64-apple-darwin.tar.gz",
                "fd-v1.2.3-x86_64-unknown-linux-musl.tar.gz.sha256",
            ]),
        )
        .unwrap();

        assert_eq!(
            scaffold,
            PluginScaffold {
                plugin_name: "fd".to_string(),
                file_name: "fd.toml".to_string(),
                contents: scaffold.contents.clone(),
            }
        );
        assert!(
            scaffold
                .contents
                .contains("asset_pattern = \"fd-{version}-{target}.tar.gz\"")
        );
        assert!(scaffold.contents.contains(
            "checksum_asset_pattern = \"fd-{version}-{target}.tar.gz.sha256\""
        ));
        assert!(
            scaffold
                .contents
                .contains("binary = \"fd-{version}-{target}/fd\"")
        );
    }

    #[test]
    fn test_build_plugin_scaffold_for_raw_binary_release() {
        let scaffold = build_plugin_scaffold(
            "jqlang/jq",
            &sample_metadata(),
            &sample_release(&["jq-linux64", "jq-macos-arm64", "sha256sum.txt"]),
        )
        .unwrap();

        assert!(
            scaffold
                .contents
                .contains("asset_pattern = \"jq-{target}\"")
        );
        assert!(scaffold.contents.contains("binary = \"jq\""));
        assert!(
            scaffold
                .contents
                .contains("checksum_asset_pattern = \"sha256sum.txt\"")
        );
    }
}
